/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#3755c3",
        "surface-container-high": "#e2e7ff",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eaedff",
        "primary": "#00288e",
        "outline-variant": "#c4c5d5",
        "on-tertiary-fixed-variant": "#930013",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#ffb3ad",
        "hairline-light": "#E2E8F0",
        "tertiary-container": "#9b0015",
        "outline": "#757684",
        "on-error": "#ffffff",
        "graphite-deep": "#0B0F17",
        "surface-variant": "#dae2fd",
        "graphite-border": "#1E293B",
        "on-secondary-fixed-variant": "#004b73",
        "primary-container": "#1e40af",
        "surface": "#faf8ff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#001d31",
        "secondary-fixed-dim": "#93ccff",
        "on-background": "#131b2e",
        "on-primary-fixed": "#001453",
        "surface-container-low": "#f2f3ff",
        "inverse-on-surface": "#eef0ff",
        "graphite-surface": "#111827",
        "on-primary-container": "#a8b8ff",
        "secondary": "#006398",
        "canvas-light": "#FBFBFA",
        "inverse-primary": "#b8c4ff",
        "on-secondary": "#ffffff",
        "tertiary": "#70000c",
        "on-secondary-container": "#00476e",
        "inverse-surface": "#283044",
        "surface-container-highest": "#dae2fd",
        "background": "#faf8ff",
        "electric-glow": "#38BDF8",
        "secondary-container": "#5bb8fe",
        "secondary-fixed": "#cce5ff",
        "surface-bright": "#faf8ff",
        "on-surface": "#131b2e",
        "primary-fixed-dim": "#b8c4ff",
        "on-tertiary-fixed": "#410004",
        "on-primary-fixed-variant": "#173bab",
        "error": "#ba1a1a",
        "on-surface-variant": "#444653",
        "surface-card": "#FFFFFF",
        "on-error-container": "#93000a",
        "primary-fixed": "#dde1ff",
        "pierc-slate": "#3A6382",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffdad7",
        "surface-dim": "#d2d9f4",
        "on-tertiary-container": "#ffa39c"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        full: "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        gutter: "1.5rem",
        "gutter-sm": "1rem",
        margin: "2rem",
        "margin-sm": "1rem",
        "margin-lg": "4rem"
      },
      fontFamily: {
        "display-hero": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "metric-display": ["Plus Jakarta Sans", "sans-serif"],
        "metric-display-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Geist", "sans-serif"],
        "label-code": ["Geist", "monospace"],
        sans: ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-hero": ["72px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "display-hero-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-xl-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "metric-display": ["56px", { lineHeight: "60px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "metric-display-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-code": ["12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
