/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#fdf2f4",
        "surface-container-highest": "#fce7ec",
        "canvas-light": "#fcfbfc",
        "surface-bright": "#fff9fa",
        "deep-rose": "#9f1239",
        "on-error": "#ffffff",
        "background": "#fff9fa",
        "surface-container-high": "#fce1e7",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#283044",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#ffb3b6",
        "outline-variant": "#f3cbd2",
        "on-primary-fixed": "#40000c",
        "graphite-border": "#1e293b",
        "primary-container": "#e11d48",
        "surface-tint": "#be0037",
        "graphite-deep": "#080b11",
        "secondary": "#db2777",
        "secondary-fixed": "#ffd9dd",
        "on-surface-variant": "#644047",
        "on-tertiary-container": "#fffaf9",
        "glow-pink": "rgba(225, 29, 72, 0.28)",
        "tertiary-fixed-dim": "#ffb2b7",
        "surface-dim": "#f8d5dc",
        "on-secondary-fixed-variant": "#8a1538",
        "on-primary": "#ffffff",
        "raspberry-obsidian": "#4c0519",
        "on-secondary-fixed": "#400014",
        "on-secondary-container": "#6f0028",
        "on-primary-container": "#fffaf9",
        "inverse-primary": "#ffb3b6",
        "error": "#ba1a1a",
        "secondary-container": "#fd6f8c",
        "on-tertiary-fixed": "#40000d",
        "surface": "#fff9fa",
        "fuchsia-vivid": "#db2777",
        "outline": "#9f6e77",
        "on-surface": "#191216",
        "on-primary-fixed-variant": "#920028",
        "primary-fixed": "#ffdada",
        "tertiary": "#b70438",
        "tertiary-container": "#db2b4e",
        "graphite-surface": "#0f172a",
        "tertiary-fixed": "#ffdadb",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#ffb2bd",
        "surface-variant": "#fce7ec",
        "rose-laser": "#fb7185",
        "on-tertiary-fixed-variant": "#92002a",
        "on-secondary": "#ffffff",
        "primary": "#e11d48",
        "surface-card": "#ffffff",
        "surface-container": "#fdebed",
        "on-background": "#191216",
        "inverse-on-surface": "#eef0ff",
        "hairline-light": "#f7e6e9",
        "electric-pink": "#f43f5e",
        "electric-glow": "#f43f5e",
        "pierc-slate": "#4c0519"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        full: "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        gutter: "1.5rem",
        "gutter-sm": "1rem",
        margin: "2rem",
        "margin-sm": "1rem",
        "margin-lg": "4rem"
      },
      fontFamily: {
        "display-hero": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "metric-display": ["Plus Jakarta Sans", "sans-serif"],
        "metric-display-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Geist", "sans-serif"],
        "label-code": ["Geist", "monospace"],
        sans: ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-hero": ["72px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "display-hero-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-xl-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "metric-display": ["56px", { lineHeight: "60px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "metric-display-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-code": ["12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
